/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cvsong_study_rice_ndk_JniUtil */

#ifndef _Included_com_cvsong_study_rice_ndk_JniUtil
#define _Included_com_cvsong_study_rice_ndk_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cvsong_study_rice_ndk_JniUtil
 * Method:    getRsaKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cvsong_study_rice_ndk_JniUtil_getRsaKey
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
